Global:
  device: gpu
  epoch_num: 5
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/sar
  eval_epoch_step: [0, 1]
  cal_metric_during_train: true
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_mode: false
  infer_img: doc/imgs_words/en/word_1.png
  character_dict_path: &character_dict_path ppocr/utils/dict90.txt
  max_text_length: &max_text_length 30
  use_space_char: &use_space_char False
  rm_symbol: &rm_symbol True

Export:
  export_dir:
  export_shape: [ 1, 3, 48, 160 ]
  dynamic_axes: []

Optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0

LRScheduler:
  name: MultiStepLR
  milestones: [3,4]
  warmup_epoch: 0

Architecture:
  model_type: rec
  algorithm: SAR
  Transform:
  Backbone:
    name: ResNet31
  Head:
    name: SARHead

Loss:
  name: SARLoss

PostProcess:
  name: SARLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char
  rm_symbol: *rm_symbol

Metric:
  name: RecMetric


Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SARLabelEncode: # Class handling label
      - SARRecResizeImg:
          image_shape: [3, 48, 48, 160] # h:48 w:[48,160]
          width_downsample_ratio: 0.25
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/validation/
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SARLabelEncode: # Class handling label
      - SARRecResizeImg:
          image_shape: [3, 48, 48, 160]
          width_downsample_ratio: 0.25
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4

